version: "1.0"
info:
  model: int-scaffold
packages:
- name: Testf1Project
  gitServerName: aa1
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
  wpmVersion: latest
